### ISSUE TITLE
64-bit binary

### ISSUE THREAD

**Issue by Reel-Deal** [Aktanusa/VFRtoCFR#1]
Hi Aktan,

I see on the changelog that a 64-bit dll was released , however I don't see it the releases section. It would be nice to have an official release on GitHub. Right now the AviSynth wiki has a MediaFire link. Thank you.

**Comment by Aktanusa** [comment]
I guess I can do that.  Does the MediaFire link not work?  I wrote this plugin a long time ago and just finally put it on GitHub as storage.

Edit:  I see the problem now.  There is no 64-bit release.  Sorry about that.  I can build one.

**Comment by Reel-Deal** [comment]
Awesome. Thank you very much

**Comment by Aktanusa** [comment]
I've added the release.  Enjoy!
